#!/usr/bin/env python3
"""Create .properties files for UI translations."""

import os

translations = {
    'fr': {
        'app.title': 'Vocabulaire Français',
        'tab.study': 'Étude',
        'tab.stats': 'Statistiques',
        'tab.settings': 'Réglages',
        'session.counter': '{done} / {total} cartes',
        'btn.show': 'Afficher',
        'btn.exclude': 'Exclure',
        'btn.continue': 'Continuer',
        'section.definition': 'Définition',
        'section.etymology': 'Étymologie',
        'msg.correct': 'Correct !',
        'stats.title.forecast': 'Prévisions de révision',
        'forecast.days.7': '7 jours',
        'forecast.days.30': '30 jours',
        'stats.label.started': 'Commencées',
        'stats.label.new': 'Nouvelles',
        'stats.label.learning': 'En apprentissage',
        'stats.label.review': 'À réviser',
        'stats.label.time': 'Temps estimé',
        'streak.label': 'jour{plural} de suite',
        'word.search.placeholder': 'Filtrer par mot...',
        'table.header.word': 'Mot',
        'table.header.tense': 'Temps',
        'table.header.interval': 'Intervalle',
        'table.header.ease': 'Facilité',
        'table.header.due': 'Échéance',
        'table.header.status': 'Statut',
        'status.new': 'New',
        'status.learning': 'Learning',
        'status.review': 'Review',
        'status.mature': 'Mature',
        'status.excluded': 'Excluded',
        'btn.reactivate': 'Réactiver',
        'settings.new.cards': 'Nouvelles cartes par jour',
        'settings.data': 'Données',
        'btn.export': 'Exporter la progression',
        'btn.import': 'Importer la progression',
        'modal.avalanche.title': 'Avalanche de révisions',
        'modal.avalanche.text': 'Lorsque vous introduisez un nombre illimité de nouvelles cartes, chaque carte révisée aujourd\'hui génère des révisions futures. En quelques jours, vous pourriez vous retrouver avec des centaines de cartes dues le même jour.',
        'modal.avalanche.text2': 'Ce phénomène est appelé une « avalanche de révisions ». Il peut être décourageant et mener à l\'abandon de l\'apprentissage.',
        'modal.avalanche.text3': 'Il est recommandé de commencer avec 10 à 20 nouvelles cartes par jour pour maintenir une charge de révision gérable à long terme.',
        'modal.close': 'Fermer',
        'empty.title': 'Félicitations !',
        'empty.message': 'Toutes les cartes du jour sont terminées.',
        'empty.next': 'Revenez demain pour de nouvelles révisions.',
        'confirm.exclude': 'Cette carte sera définitivement exclue de vos révisions. Vous pourrez la réactiver dans l\'onglet Statistiques.\n\nContinuer ?',
        'alert.invalid.file': 'Fichier invalide : structure incorrecte.',
        'confirm.import': 'Cela remplacera votre progression actuelle. Continuer ?',
        'alert.read.error': 'Erreur de lecture du fichier.',
        'forecast.today': 'Auj.',
        'tooltip.started': 'Nombre total de cartes commencées sur toutes les cartes disponibles',
        'tooltip.new': 'Nouvelles cartes disponibles aujourd\'hui selon votre limite quotidienne',
        'tooltip.learning': 'Cartes actuellement en phase d\'apprentissage (intervalles courts)',
        'tooltip.review': 'Cartes déjà apprises qui sont à réviser aujourd\'hui',
        'tooltip.time': 'Temps estimé pour compléter toutes les cartes dues aujourd\'hui',
        'tooltip.col.word': 'Le mot ou l\'expression en français',
        'tooltip.col.tense': 'Temps grammatical utilisé dans la phrase',
        'tooltip.col.interval': 'Jours avant la prochaine révision',
        'tooltip.col.ease': 'Facteur de difficulté (2.5 = normal, plus bas = plus difficile)',
        'tooltip.col.due': 'Date de la prochaine révision',
        'tooltip.col.status': 'Statut actuel d\'apprentissage de la carte',
    },
    'en': {
        'app.title': 'French Vocabulary',
        'tab.study': 'Study',
        'tab.stats': 'Statistics',
        'tab.settings': 'Settings',
        'session.counter': '{done} / {total} cards',
        'btn.show': 'Show',
        'btn.exclude': 'Exclude',
        'btn.continue': 'Continue',
        'section.definition': 'Definition',
        'section.etymology': 'Etymology',
        'msg.correct': 'Correct!',
        'stats.title.forecast': 'Review forecast',
        'forecast.days.7': '7 days',
        'forecast.days.30': '30 days',
        'stats.label.started': 'Started',
        'stats.label.new': 'New',
        'stats.label.learning': 'Learning',
        'stats.label.review': 'To review',
        'stats.label.time': 'Estimated time',
        'streak.label': 'day{plural} streak',
        'word.search.placeholder': 'Filter by word...',
        'table.header.word': 'Word',
        'table.header.tense': 'Tense',
        'table.header.interval': 'Interval',
        'table.header.ease': 'Ease',
        'table.header.due': 'Due',
        'table.header.status': 'Status',
        'status.new': 'New',
        'status.learning': 'Learning',
        'status.review': 'Review',
        'status.mature': 'Mature',
        'status.excluded': 'Excluded',
        'btn.reactivate': 'Reactivate',
        'settings.new.cards': 'New cards per day',
        'settings.data': 'Data',
        'btn.export': 'Export progress',
        'btn.import': 'Import progress',
        'modal.avalanche.title': 'Review avalanche',
        'modal.avalanche.text': 'When you introduce unlimited new cards, each card reviewed today generates future reviews. In a few days, you could find yourself with hundreds of cards due on the same day.',
        'modal.avalanche.text2': 'This phenomenon is called a "review avalanche". It can be discouraging and lead to abandoning learning.',
        'modal.avalanche.text3': 'It is recommended to start with 10 to 20 new cards per day to maintain a manageable review load in the long term.',
        'modal.close': 'Close',
        'empty.title': 'Congratulations!',
        'empty.message': 'All cards for today are finished.',
        'empty.next': 'Come back tomorrow for new reviews.',
        'confirm.exclude': 'This card will be permanently excluded from your reviews. You can reactivate it in the Statistics tab.\n\nContinue?',
        'alert.invalid.file': 'Invalid file: incorrect structure.',
        'confirm.import': 'This will replace your current progress. Continue?',
        'alert.read.error': 'Error reading file.',
        'forecast.today': 'Today',
        'tooltip.started': 'Total cards you have started learning out of all available cards',
        'tooltip.new': 'New cards available to study today based on your daily limit',
        'tooltip.learning': 'Cards currently in the learning phase (short intervals)',
        'tooltip.review': 'Previously learned cards that are due for review today',
        'tooltip.time': 'Estimated time to complete all due cards today',
        'tooltip.col.word': 'The French word or phrase',
        'tooltip.col.tense': 'Grammatical tense used in the sentence',
        'tooltip.col.interval': 'Days until next review',
        'tooltip.col.ease': 'Difficulty factor (2.5 = normal, lower = harder)',
        'tooltip.col.due': 'Date when card is next due for review',
        'tooltip.col.status': 'Current learning status of the card',
    },
    'de': {
        'app.title': 'Französischer Wortschatz',
        'tab.study': 'Lernen',
        'tab.stats': 'Statistiken',
        'tab.settings': 'Einstellungen',
        'session.counter': '{done} / {total} Karten',
        'btn.show': 'Anzeigen',
        'btn.exclude': 'Ausschließen',
        'btn.continue': 'Fortfahren',
        'section.definition': 'Definition',
        'section.etymology': 'Etymologie',
        'msg.correct': 'Richtig!',
        'stats.title.forecast': 'Wiederholungsprognose',
        'forecast.days.7': '7 Tage',
        'forecast.days.30': '30 Tage',
        'stats.label.started': 'Gestartet',
        'stats.label.new': 'Neu',
        'stats.label.learning': 'Lernen',
        'stats.label.review': 'Zu wiederholen',
        'stats.label.time': 'Geschätzte Zeit',
        'streak.label': '{number} Tag{plural} Erfolgsserie',
        'word.search.placeholder': 'Nach Wort filtern...',
        'table.header.word': 'Wort',
        'table.header.tense': 'Zeit',
        'table.header.interval': 'Intervall',
        'table.header.ease': 'Leichtigkeit',
        'table.header.due': 'Fällig',
        'table.header.status': 'Status',
        'status.new': 'Neu',
        'status.learning': 'Lernen',
        'status.review': 'Überprüfung',
        'status.mature': 'Reif',
        'status.excluded': 'Ausgeschlossen',
        'btn.reactivate': 'Reaktivieren',
        'settings.new.cards': 'Neue Karten pro Tag',
        'settings.data': 'Daten',
        'btn.export': 'Fortschritt exportieren',
        'btn.import': 'Fortschritt importieren',
        'modal.avalanche.title': 'Wiederholungs-Lawine',
        'modal.avalanche.text': 'Wenn Sie unbegrenzte neue Karten einführen, generiert jede heute überprüfte Karte zukünftige Wiederholungen. In wenigen Tagen könnten Sie Hunderte von Karten haben, die am selben Tag fällig sind.',
        'modal.avalanche.text2': 'Dieses Phänomen wird als "Wiederholungs-Lawine" bezeichnet. Es kann entmutigend sein und zum Aufgeben des Lernens führen.',
        'modal.avalanche.text3': 'Es wird empfohlen, mit 10 bis 20 neuen Karten pro Tag zu beginnen, um langfristig eine überschaubare Wiederholungslast zu erhalten.',
        'modal.close': 'Schließen',
        'empty.title': 'Glückwunsch!',
        'empty.message': 'Alle Karten für heute sind fertig.',
        'empty.next': 'Kommen Sie morgen zurück für neue Wiederholungen.',
        'confirm.exclude': 'Diese Karte wird dauerhaft aus Ihren Wiederholungen ausgeschlossen. Sie können sie auf der Registerkarte Statistiken erneut aktivieren.\n\nFortfahren?',
        'alert.invalid.file': 'Ungültige Datei: falsche Struktur.',
        'confirm.import': 'Dies ersetzt Ihren aktuellen Fortschritt. Fortfahren?',
        'alert.read.error': 'Fehler beim Lesen der Datei.',
        'forecast.today': 'Heute',
        'tooltip.started': 'Gesamtzahl der begonnenen Karten von allen verfügbaren Karten',
        'tooltip.new': 'Neue Karten, die heute basierend auf Ihrem Tageslimit verfügbar sind',
        'tooltip.learning': 'Karten, die sich derzeit in der Lernphase befinden (kurze Intervalle)',
        'tooltip.review': 'Bereits gelernte Karten, die heute zur Wiederholung fällig sind',
        'tooltip.time': 'Geschätzte Zeit, um alle heute fälligen Karten abzuschließen',
        'tooltip.col.word': 'Das französische Wort oder die Redewendung',
        'tooltip.col.tense': 'Im Satz verwendete grammatische Zeitform',
        'tooltip.col.interval': 'Tage bis zur nächsten Wiederholung',
        'tooltip.col.ease': 'Schwierigkeitsfaktor (2,5 = normal, niedriger = schwieriger)',
        'tooltip.col.due': 'Datum der nächsten Wiederholung',
        'tooltip.col.status': 'Aktueller Lernstatus der Karte',
    },
    'es': {
        'app.title': 'Vocabulario Francés',
        'tab.study': 'Estudio',
        'tab.stats': 'Estadísticas',
        'tab.settings': 'Configuración',
        'session.counter': '{done} / {total} tarjetas',
        'btn.show': 'Mostrar',
        'btn.exclude': 'Excluir',
        'btn.continue': 'Continuar',
        'section.definition': 'Definición',
        'section.etymology': 'Etimología',
        'msg.correct': '¡Correcto!',
        'stats.title.forecast': 'Pronóstico de revisión',
        'forecast.days.7': '7 días',
        'forecast.days.30': '30 días',
        'stats.label.started': 'Iniciadas',
        'stats.label.new': 'Nuevas',
        'stats.label.learning': 'Aprendiendo',
        'stats.label.review': 'Por revisar',
        'stats.label.time': 'Tiempo estimado',
        'streak.label': '{number} día{plural} de racha',
        'word.search.placeholder': 'Filtrar por palabra...',
        'table.header.word': 'Palabra',
        'table.header.tense': 'Tiempo',
        'table.header.interval': 'Intervalo',
        'table.header.ease': 'Facilidad',
        'table.header.due': 'Vencimiento',
        'table.header.status': 'Estado',
        'status.new': 'Nuevo',
        'status.learning': 'Aprendiendo',
        'status.review': 'Revisión',
        'status.mature': 'Maduro',
        'status.excluded': 'Excluido',
        'btn.reactivate': 'Reactivar',
        'settings.new.cards': 'Tarjetas nuevas por día',
        'settings.data': 'Datos',
        'btn.export': 'Exportar progreso',
        'btn.import': 'Importar progreso',
        'modal.avalanche.title': 'Alud de revisión',
        'modal.avalanche.text': 'Cuando introduce tarjetas nuevas ilimitadas, cada tarjeta revisada hoy genera futuras revisiones. En unos pocos días, podría encontrarse con cientos de tarjetas vencidas el mismo día.',
        'modal.avalanche.text2': 'Este fenómeno se llama "alud de revisión". Puede ser desalentador y llevar al abandono del aprendizaje.',
        'modal.avalanche.text3': 'Se recomienda comenzar con 10 a 20 tarjetas nuevas por día para mantener una carga de revisión manejable a largo plazo.',
        'modal.close': 'Cerrar',
        'empty.title': '¡Felicidades!',
        'empty.message': 'Todas las tarjetas de hoy han terminado.',
        'empty.next': 'Vuelva mañana para nuevas revisiones.',
        'confirm.exclude': 'Esta tarjeta será excluida permanentemente de sus revisiones. Puede reactivarla en la pestaña Estadísticas.\n\n¿Continuar?',
        'alert.invalid.file': 'Archivo inválido: estructura incorrecta.',
        'confirm.import': 'Esto reemplazará su progreso actual. ¿Continuar?',
        'alert.read.error': 'Error al leer el archivo.',
        'forecast.today': 'Hoy',
        'tooltip.started': 'Total de tarjetas iniciadas de todas las tarjetas disponibles',
        'tooltip.new': 'Tarjetas nuevas disponibles hoy según su límite diario',
        'tooltip.learning': 'Tarjetas actualmente en fase de aprendizaje (intervalos cortos)',
        'tooltip.review': 'Tarjetas ya aprendidas que deben revisarse hoy',
        'tooltip.time': 'Tiempo estimado para completar todas las tarjetas de hoy',
        'tooltip.col.word': 'La palabra o expresión en francés',
        'tooltip.col.tense': 'Tiempo gramatical usado en la oración',
        'tooltip.col.interval': 'Días hasta la próxima revisión',
        'tooltip.col.ease': 'Factor de dificultad (2,5 = normal, menor = más difícil)',
        'tooltip.col.due': 'Fecha de la próxima revisión',
        'tooltip.col.status': 'Estado actual de aprendizaje de la tarjeta',
    },
    'it': {
        'app.title': 'Vocabolario Francese',
        'tab.study': 'Studio',
        'tab.stats': 'Statistiche',
        'tab.settings': 'Impostazioni',
        'session.counter': '{done} / {total} carte',
        'btn.show': 'Mostra',
        'btn.exclude': 'Escludi',
        'btn.continue': 'Continua',
        'section.definition': 'Definizione',
        'section.etymology': 'Etimologia',
        'msg.correct': 'Corretto!',
        'stats.title.forecast': 'Previsione di revisione',
        'forecast.days.7': '7 giorni',
        'forecast.days.30': '30 giorni',
        'stats.label.started': 'Iniziate',
        'stats.label.new': 'Nuove',
        'stats.label.learning': 'In corso',
        'stats.label.review': 'Da rivedere',
        'stats.label.time': 'Tempo stimato',
        'streak.label': '{number} giorno{plural} di serie',
        'word.search.placeholder': 'Filtra per parola...',
        'table.header.word': 'Parola',
        'table.header.tense': 'Tempo',
        'table.header.interval': 'Intervallo',
        'table.header.ease': 'Facilità',
        'table.header.due': 'Scadenza',
        'table.header.status': 'Stato',
        'status.new': 'Nuovo',
        'status.learning': 'In corso',
        'status.review': 'Revisione',
        'status.mature': 'Maturo',
        'status.excluded': 'Escluso',
        'btn.reactivate': 'Riattiva',
        'settings.new.cards': 'Nuove carte al giorno',
        'settings.data': 'Dati',
        'btn.export': 'Esporta progresso',
        'btn.import': 'Importa progresso',
        'modal.avalanche.title': 'Valanga di revisioni',
        'modal.avalanche.text': 'Quando si introducono carte nuove illimitate, ogni carta rivista oggi genera revisioni future. In pochi giorni, potresti trovarti con centinaia di carte dovute nello stesso giorno.',
        'modal.avalanche.text2': 'Questo fenomeno è chiamato "valanga di revisioni". Può essere scoraggiante e portare all\'abbandono dell\'apprendimento.',
        'modal.avalanche.text3': 'Si consiglia di iniziare con 10-20 carte nuove al giorno per mantenere un carico di revisione gestibile a lungo termine.',
        'modal.close': 'Chiudi',
        'empty.title': 'Complimenti!',
        'empty.message': 'Tutte le carte di oggi sono terminate.',
        'empty.next': 'Torna domani per nuove revisioni.',
        'confirm.exclude': 'Questa carta sarà esclusa permanentemente dalle tue revisioni. Potrai riattivarla nella scheda Statistiche.\n\nContinuare?',
        'alert.invalid.file': 'File non valido: struttura errata.',
        'confirm.import': 'Questo sostituirà il tuo progresso attuale. Continuare?',
        'alert.read.error': 'Errore nella lettura del file.',
        'forecast.today': 'Oggi',
        'tooltip.started': 'Totale carte iniziate su tutte le carte disponibili',
        'tooltip.new': 'Nuove carte disponibili oggi in base al limite giornaliero',
        'tooltip.learning': 'Carte attualmente in fase di apprendimento (intervalli brevi)',
        'tooltip.review': 'Carte già apprese che devono essere riviste oggi',
        'tooltip.time': 'Tempo stimato per completare tutte le carte di oggi',
        'tooltip.col.word': 'La parola o espressione francese',
        'tooltip.col.tense': 'Tempo grammaticale usato nella frase',
        'tooltip.col.interval': 'Giorni fino alla prossima revisione',
        'tooltip.col.ease': 'Fattore di difficoltà (2,5 = normale, più basso = più difficile)',
        'tooltip.col.due': 'Data della prossima revisione',
        'tooltip.col.status': 'Stato attuale di apprendimento della carta',
    },
    'pl': {
        'app.title': 'Francuski Słownik',
        'tab.study': 'Nauka',
        'tab.stats': 'Statystyki',
        'tab.settings': 'Ustawienia',
        'session.counter': '{done} / {total} kart',
        'btn.show': 'Pokaż',
        'btn.exclude': 'Wyklucz',
        'btn.continue': 'Kontynuuj',
        'section.definition': 'Definicja',
        'section.etymology': 'Etymologia',
        'msg.correct': 'Poprawnie!',
        'stats.title.forecast': 'Prognoza powtórzeń',
        'forecast.days.7': '7 dni',
        'forecast.days.30': '30 dni',
        'stats.label.started': 'Rozpoczęte',
        'stats.label.new': 'Nowe',
        'stats.label.learning': 'Uczenie się',
        'stats.label.review': 'Do przeglądu',
        'stats.label.time': 'Szacunkowy czas',
        'streak.label': '{number} dzień{plural} serii',
        'word.search.placeholder': 'Filtruj po słowie...',
        'table.header.word': 'Słowo',
        'table.header.tense': 'Czas',
        'table.header.interval': 'Przedział',
        'table.header.ease': 'Łatwość',
        'table.header.due': 'Termin',
        'table.header.status': 'Status',
        'status.new': 'Nowe',
        'status.learning': 'Uczenie się',
        'status.review': 'Przegląd',
        'status.mature': 'Dojrzałe',
        'status.excluded': 'Wykluczone',
        'btn.reactivate': 'Reaktywuj',
        'settings.new.cards': 'Nowe karty dziennie',
        'settings.data': 'Dane',
        'btn.export': 'Eksportuj postęp',
        'btn.import': 'Importuj postęp',
        'modal.avalanche.title': 'Lawina powtórzeń',
        'modal.avalanche.text': 'Gdy wprowadzasz nieograniczone nowe karty, każda karta przejrzana dzisiaj generuje przyszłe powtórzenia. Za kilka dni możesz znaleźć się z setkami kart do robienia tego samego dnia.',
        'modal.avalanche.text2': 'To zjawisko nazywane jest "lawiną powtórzeń". Może być zniechęcające i prowadzić do porzucenia nauki.',
        'modal.avalanche.text3': 'Zaleca się zaczynanie z 10-20 nowymi kartami dziennie, aby utrzymać zarządzalny obciążenie powtórzeniami na dłuższą metę.',
        'modal.close': 'Zamknij',
        'empty.title': 'Gratulacje!',
        'empty.message': 'Wszystkie karty na dzisiaj są skończone.',
        'empty.next': 'Wróć jutro na nowe powtórzenia.',
        'confirm.exclude': 'Ta karta będzie na stałe wykluczona z Twoich powtórzeń. Możesz ją reaktywować w karcie Statystyki.\n\nKontynuować?',
        'alert.invalid.file': 'Nieprawidłowy plik: nieprawidłowa struktura.',
        'confirm.import': 'Spowoduje to zastąpienie Twojego obecnego postępu. Kontynuować?',
        'alert.read.error': 'Błąd odczytu pliku.',
        'forecast.today': 'Dzisiaj',
        'tooltip.started': 'Łączna liczba rozpoczętych kart ze wszystkich dostępnych',
        'tooltip.new': 'Nowe karty dostępne dzisiaj według dziennego limitu',
        'tooltip.learning': 'Karty aktualnie w fazie nauki (krótkie interwały)',
        'tooltip.review': 'Wcześniej nauczone karty, które dziś wymagają powtórzenia',
        'tooltip.time': 'Szacowany czas na ukończenie wszystkich dzisiejszych kart',
        'tooltip.col.word': 'Francuskie słowo lub wyrażenie',
        'tooltip.col.tense': 'Czas gramatyczny użyty w zdaniu',
        'tooltip.col.interval': 'Dni do następnej powtórki',
        'tooltip.col.ease': 'Współczynnik trudności (2,5 = normalny, niższy = trudniejszy)',
        'tooltip.col.due': 'Data następnej powtórki',
        'tooltip.col.status': 'Aktualny status nauki karty',
    }
}

# Create lang_source directory if it doesn't exist
os.makedirs('lang_source', exist_ok=True)

# Write properties files
for lang, strings in translations.items():
    filepath = f'lang_source/ui_{lang}.properties'
    with open(filepath, 'w', encoding='utf-8') as f:
        for key in sorted(strings.keys()):
            value = strings[key]
            f.write(f'{key}={value}\n')
    print(f'Created {filepath}')

print('Done! Created 6 .properties files for UI translations')
